# Generated by Django 5.1 on 2025-12-28 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodordering', '0004_foodtracking_orderaddress_paymentdetails_review_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PaymentDetails',
            new_name='PaymentDetail',
        ),
    ]
